# Generated by Django 5.1.1 on 2024-10-31 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='put',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('count', models.IntegerField(default=0)),
                ('writer', models.CharField(default='anonymous', max_length=30)),
                ('passwd', models.CharField(max_length=30)),
                ('create_date', models.DateTimeField()),
            ],
        ),
    ]
